# Generated by Django 3.2.23 on 2024-01-14 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('signup_otp', models.CharField(max_length=4)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(error_messages={'required': 'Password cannot be null'}, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('postId', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 1, 14, 23, 28, 52, 568681))),
                ('like_count', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('post_data', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
