# Generated by Django 3.2.23 on 2024-01-15 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_postdata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='user_id',
            new_name='postuserid',
        ),
        migrations.AlterField(
            model_name='postdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 55, 56, 574517)),
        ),
    ]
