# Generated by Django 3.2.23 on 2024-01-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20240115_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 22, 4, 31, 707504)),
        ),
    ]
